/**
 * Generates supabase/seed.sql from the content bundled in src/lib/data.ts, so the CMS starts
 * with everything currently on the site. Run with:  npx tsx scripts/generate-seed.ts
 */
import { writeFileSync } from "node:fs";
import { blogPosts, projects, properties } from "../src/lib/data";

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (Array.isArray(v)) return `array[${v.map(q).join(", ")}]::text[]`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const insert = (table: string, rows: Record<string, unknown>[]) => {
  if (!rows.length) return "";
  const cols = Object.keys(rows[0]);
  const values = rows.map((r) => `  (${cols.map((c) => q(r[c])).join(", ")})`).join(",\n");
  return (
    `insert into public.${table} (${cols.join(", ")}) overriding system value values\n${values}\n` +
    `on conflict (id) do nothing;\n` +
    // Keep the identity sequence ahead of the explicit ids we just inserted
    `select setval(pg_get_serial_sequence('public.${table}', 'id'), (select max(id) from public.${table}));\n\n`
  );
};

const sql =
  `-- Generated by scripts/generate-seed.ts from src/lib/data.ts. Safe to re-run.\n\n` +
  insert(
    "properties",
    properties.map((p) => ({
      id: p.id,
      title: p.title,
      type: p.type,
      status: p.status,
      price: p.price,
      location: p.location,
      address: p.address,
      bedrooms: p.bedrooms ?? null,
      bathrooms: p.bathrooms ?? null,
      size: p.size,
      description: p.description,
      features: p.features,
      image_url: p.imageUrl,
      images: p.images,
      year_built: p.yearBuilt ?? null,
      parking: p.parking ?? null,
      furnished: p.furnished ?? null,
      agent_name: p.agent.name,
      agent_phone: p.agent.phone,
      agent_email: p.agent.email,
      featured: false,
      published: true,
      date_added: p.dateAdded,
    })),
  ) +
  insert(
    "projects",
    projects.map((p, i) => ({
      id: p.id,
      title: p.title,
      description: p.description,
      location: p.location,
      category: p.category ?? "Residential",
      project_status: p.projectStatus ?? "Completed",
      image_url: p.imageUrl,
      gallery: p.gallery ?? [],
      completion_year: p.completionYear ?? null,
      size: p.size ?? "",
      features: p.features ?? [],
      featured: p.featured ?? false,
      published: true,
      sort_order: i,
    })),
  ) +
  insert(
    "blog_posts",
    blogPosts.map((b) => ({
      id: b.id,
      title: b.title,
      slug: b.slug,
      excerpt: b.excerpt,
      content: b.content,
      image_url: b.imageUrl,
      category: b.category,
      tags: b.tags,
      author: b.author,
      author_role: b.authorRole ?? null,
      author_image_url: b.authorImageUrl ?? null,
      read_time: b.readTime,
      published: true,
      published_at: b.date,
    })),
  );

writeFileSync("supabase/seed.sql", sql);
console.log(
  `Wrote supabase/seed.sql: ${properties.length} properties, ${projects.length} projects, ${blogPosts.length} blog posts`,
);
