-- First-party, privacy-friendly analytics. No cookies, no IPs, no personal data:
-- a random per-tab session id, the page, where the visit came from, device class and time zone.

create table public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id uuid not null,
  name text not null check (name in (
    'pageview', 'call_click', 'email_click', 'whatsapp_click', 'share', 'contact_submit'
  )),
  path text not null check (char_length(path) between 1 and 300),
  referrer_host text check (char_length(referrer_host) <= 200),
  utm_source text check (char_length(utm_source) <= 100),
  device text check (device in ('mobile', 'tablet', 'desktop')),
  timezone text check (char_length(timezone) <= 64)
);

create index analytics_events_created_idx on public.analytics_events (created_at desc);
create index analytics_events_name_created_idx on public.analytics_events (name, created_at desc);

alter table public.analytics_events enable row level security;

-- Visitors may only add events (never read, change or delete them)
create policy "Anyone can record events" on public.analytics_events
  for insert to anon, authenticated
  with check (created_at > now() - interval '1 minute' and created_at < now() + interval '1 minute');

create policy "Admins can read events" on public.analytics_events
  for select to authenticated
  using ((select private.is_admin()));

create policy "Admins can delete events" on public.analytics_events
  for delete to authenticated
  using ((select private.is_admin()));

-- Dashboard summary. SECURITY INVOKER, so it only sees rows the caller's RLS allows:
-- admins get the numbers, everyone else gets zeros.
create or replace function public.analytics_summary(days integer default 30)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  with bounds as (
    select
      now() - make_interval(days => days) as start_at,
      now() - make_interval(days => days * 2) as prev_start_at
  ),
  cur as (
    select e.* from public.analytics_events e, bounds b where e.created_at >= b.start_at
  ),
  prev as (
    select e.* from public.analytics_events e, bounds b
    where e.created_at >= b.prev_start_at and e.created_at < b.start_at
  ),
  pv as (select * from cur where name = 'pageview')
  select jsonb_build_object(
    'totals', jsonb_build_object(
      'pageviews', (select count(*) from pv),
      'visits', (select count(distinct session_id) from pv),
      'contacts', (select count(*) from cur where name <> 'pageview'),
      'prev_pageviews', (select count(*) from prev where name = 'pageview'),
      'prev_visits', (select count(distinct session_id) from prev where name = 'pageview'),
      'prev_contacts', (select count(*) from prev where name <> 'pageview'),
      'live', (select count(distinct session_id) from public.analytics_events
               where created_at > now() - interval '5 minutes')
    ),
    'daily', coalesce((
      select jsonb_agg(jsonb_build_object('day', d.day, 'visits', coalesce(x.visits, 0), 'pageviews', coalesce(x.pageviews, 0)) order by d.day)
      from generate_series(
        (now() at time zone 'Africa/Lagos')::date - (days - 1),
        (now() at time zone 'Africa/Lagos')::date,
        interval '1 day'
      ) as d(day)
      left join (
        select (created_at at time zone 'Africa/Lagos')::date as day,
               count(distinct session_id) as visits, count(*) as pageviews
        from pv group by 1
      ) x on x.day = d.day::date
    ), '[]'::jsonb),
    'top_pages', coalesce((
      select jsonb_agg(t) from (
        select path, count(*) as views from pv group by path order by views desc limit 8
      ) t
    ), '[]'::jsonb),
    'top_properties', coalesce((
      select jsonb_agg(t) from (
        select p.id, p.title, count(*) as views
        from pv
        join public.properties p on pv.path = '/properties/' || p.id
        group by p.id, p.title order by views desc limit 6
      ) t
    ), '[]'::jsonb),
    'sources', coalesce((
      select jsonb_agg(t) from (
        select coalesce(nullif(utm_source, ''), nullif(referrer_host, ''), 'Direct') as source,
               count(distinct session_id) as visits
        from pv group by 1 order by visits desc limit 6
      ) t
    ), '[]'::jsonb),
    'devices', coalesce((
      select jsonb_agg(t) from (
        select coalesce(device, 'desktop') as device, count(distinct session_id) as visits
        from pv group by 1 order by visits desc
      ) t
    ), '[]'::jsonb),
    'locations', coalesce((
      select jsonb_agg(t) from (
        select coalesce(nullif(timezone, ''), 'Unknown') as timezone, count(distinct session_id) as visits
        from pv group by 1 order by visits desc limit 6
      ) t
    ), '[]'::jsonb),
    'actions', coalesce((
      select jsonb_agg(t) from (
        select name, count(*) as count from cur where name <> 'pageview' group by name order by count desc
      ) t
    ), '[]'::jsonb)
  );
$$;

revoke all on function public.analytics_summary(integer) from public, anon;
grant execute on function public.analytics_summary(integer) to authenticated;
