-- Team members shown on the Team page, editable from /admin.

create table public.team_members (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 120),
  position text not null default '',
  qualifications text not null default '',
  department text not null default 'Executive Management'
    check (department in (
      'Executive Management',
      'Project & Construction',
      'Real Estate',
      'Design & Planning',
      'Support Services',
      'Security & Logistics'
    )),
  image_url text not null default '',
  sort_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index team_members_department_sort_idx on public.team_members (department, sort_order);

create trigger team_members_updated_at
  before update on public.team_members
  for each row execute function public.set_updated_at();

alter table public.team_members enable row level security;

create policy "Published rows are public" on public.team_members
  for select to anon, authenticated
  using (published or (select private.is_admin()));

create policy "Admins can insert" on public.team_members
  for insert to authenticated
  with check ((select private.is_admin()));

create policy "Admins can update" on public.team_members
  for update to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));

create policy "Admins can delete" on public.team_members
  for delete to authenticated
  using ((select private.is_admin()));
