-- Content management for the Da'sayonce website.
-- Public visitors can read published content; only users listed in admin_users can write.

-- ---------------------------------------------------------------------------
-- Admins
-- ---------------------------------------------------------------------------
create table public.admin_users (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

-- A signed-in user may see their own admin row (the dashboard uses this to check access).
create policy "Users can read their own admin row"
  on public.admin_users for select
  to authenticated
  using (user_id = (select auth.uid()));

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Shared updated_at trigger
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Properties (listings for sale / rent)
-- ---------------------------------------------------------------------------
create table public.properties (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 3 and 200),
  type text not null check (type in ('Residential', 'Commercial', 'Land', 'Mixed-Use')),
  status text not null check (status in ('For Sale', 'For Rent', 'Sold', 'Rented')),
  price bigint not null check (price >= 0),
  location text not null,
  address text not null default '',
  bedrooms smallint check (bedrooms >= 0),
  bathrooms smallint check (bathrooms >= 0),
  size text not null default '',
  description text not null default '',
  features text[] not null default '{}',
  image_url text not null default '',
  images text[] not null default '{}',
  year_built smallint,
  parking smallint check (parking >= 0),
  furnished boolean,
  agent_name text not null default '',
  agent_phone text not null default '',
  agent_email text not null default '',
  featured boolean not null default false,
  published boolean not null default true,
  date_added date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index properties_published_date_idx on public.properties (published, date_added desc);

create trigger properties_updated_at
  before update on public.properties
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Projects (portfolio of completed / ongoing developments)
-- ---------------------------------------------------------------------------
create table public.projects (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 3 and 200),
  description text not null default '',
  location text not null default '',
  category text not null default 'Residential'
    check (category in ('Residential', 'Commercial', 'Mixed-Use', 'Renovation')),
  project_status text not null default 'Completed'
    check (project_status in ('Completed', 'Ongoing', 'Upcoming')),
  image_url text not null default '',
  gallery text[] not null default '{}',
  completion_year smallint,
  size text not null default '',
  features text[] not null default '{}',
  featured boolean not null default false,
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index projects_published_sort_idx on public.projects (published, sort_order, created_at desc);

create trigger projects_updated_at
  before update on public.projects
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Blog posts
-- ---------------------------------------------------------------------------
create table public.blog_posts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 3 and 200),
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  excerpt text not null default '',
  content text not null default '',
  image_url text not null default '',
  category text not null default 'News',
  tags text[] not null default '{}',
  author text not null default '',
  author_role text,
  author_image_url text,
  read_time smallint not null default 5 check (read_time > 0),
  published boolean not null default true,
  published_at date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index blog_posts_published_date_idx on public.blog_posts (published, published_at desc);

create trigger blog_posts_updated_at
  before update on public.blog_posts
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Row level security for content tables
-- ---------------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array['properties', 'projects', 'blog_posts'] loop
    execute format('alter table public.%I enable row level security', t);

    execute format(
      'create policy "Published rows are public" on public.%I for select to anon, authenticated using (published or (select public.is_admin()))',
      t
    );
    execute format(
      'create policy "Admins can insert" on public.%I for insert to authenticated with check ((select public.is_admin()))',
      t
    );
    execute format(
      'create policy "Admins can update" on public.%I for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))',
      t
    );
    execute format(
      'create policy "Admins can delete" on public.%I for delete to authenticated using ((select public.is_admin()))',
      t
    );
  end loop;
end;
$$;

-- ---------------------------------------------------------------------------
-- Media storage: public bucket for listing photos, admin-only uploads
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'media',
  'media',
  true,
  10485760, -- 10 MB
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'image/gif']
)
on conflict (id) do nothing;

create policy "Admins can upload media"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'media' and (select public.is_admin()));

create policy "Admins can update media"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'media' and (select public.is_admin()));

create policy "Admins can delete media"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'media' and (select public.is_admin()));
